title: Val-Auto
titlepart1: Val
titlepart2: -Auto
responsable: Valentin Bignot
siren: 892974775
siret: 89297477500017
adresse: 64, Boulevard de la liberté
codepostal: 62230
ville: Outreau
telephone: 06.40.11.24.82
email: valauto@gmail.com
facebook: Valentin Val-Auto 
linkfacebook: https://www.facebook.com/p/Val-auto-100065232441879/