title: Val-Auto
titlepart1: Val
titlepart2: -Auto
responsable: Valentin Bignot
prenom: Valentin
nom: Bignot
siren: 892974775
siret: 89297477500017
adresse: 64, Boulevard de la liberté
codepostal: 62230
ville: Outreau
telephone: 06.40.11.24.82
email: valauto@gmail.com
facebook: Valentin Val-Auto 
linkfacebook: https://www.facebook.com/p/Val-auto-100065232441879/
linkinstagram: https://www.instagram.com/val_auto_/
linkgoogle: https://www.google.com/maps/place/Val+auto/@50.7125543,1.5919108,525m/data=!3m2!1e3!4b1!4m6!3m5!1s0x47dc2d5f83c74e7d:0x891ceecbd1c67865!8m2!3d50.7125543!4d1.5919108!16s%2Fg%2F11n6s849jl?entry=ttu&g_ep=EgoyMDI1MDExNS4wIKXMDSoASAFQAw%3D%3D
hebergeur: onRender.com